# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run archive

      - name: Find zip file
        id: findzip
        run: |
          zipfile=$(find ./releases -name '*.zip')
          echo "zipfilepath=${zipfile}" >> $GITHUB_OUTPUT
          echo "zipfilename=$(basename ${zipfile})" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: previoustag
        run: |
          set -e
          comparetag=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | sed -n '2p')
          echo "comparetag: $comparetag"
          echo "comparetag=$comparetag" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: 'Changes: https://github.com/${{ github.repository }}/compare/${{ steps.previoustag.outputs.comparetag }}...${{ github.ref_name }}'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.findzip.outputs.zipfilepath }}
          asset_name: ${{ steps.findzip.outputs.zipfilename }}
          asset_content_type: application/zip